
# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/digibooth"
  [headers.values]
    Link = "<https://idealphotovercel.com/digibooth>; rel=\"canonical\""

[[headers]]
  for = "/pica-pica-booth"
  [headers.values]
    Link = "<https://idealphotovercel.com/pica-pica-booth>; rel=\"canonical\""

[[headers]]
  for = "/kpop-photo-booth"
  [headers.values]
    Link = "<https://idealphotovercel.com/kpop-photo-booth>; rel=\"canonical\""

[[headers]]
  for = "/vintage-photobooth"
  [headers.values]
    Link = "<https://idealphotovercel.com/vintage-photobooth>; rel=\"canonical\""
